name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cache-and-install:
    name: "Cache and Install dependencies"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3